allowBuilds:
  '@parcel/watcher': true
  '@prisma/engines': true
  argon2: true
  esbuild: true
  prisma: true
  unrs-resolver: true
  vue-demi: true
minimumReleaseAgeExclude:
  - eslint@10.8.0
  - happy-dom@20.11.6
