CREATE TABLE "classes" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "classes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"use_yn" varchar(1) DEFAULT 'Y' NOT NULL,
	"delete_yn" varchar(1) DEFAULT 'N' NOT NULL,
	"create_id" integer,
	"create_date" timestamp with time zone DEFAULT now() NOT NULL,
	"update_id" integer,
	"update_date" timestamp with time zone,
	"delete_id" integer,
	"delete_date" timestamp with time zone,
	"code" varchar(100) NOT NULL,
	"name" varchar(255) NOT NULL,
	"description" text,
	"category" varchar(100),
	"characteristics" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"pose_direction" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"combat_weight" text,
	"combat_style" text,
	"power_source" text,
	"signature_identity" text,
	"rendering_keywords" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"content" text,
	"metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
	CONSTRAINT "classes_code_unique" UNIQUE("code")
);
--> statement-breakpoint
CREATE TABLE "docs" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "docs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"use_yn" varchar(1) DEFAULT 'Y' NOT NULL,
	"delete_yn" varchar(1) DEFAULT 'N' NOT NULL,
	"create_id" integer,
	"create_date" timestamp with time zone DEFAULT now() NOT NULL,
	"update_id" integer,
	"update_date" timestamp with time zone,
	"delete_id" integer,
	"delete_date" timestamp with time zone,
	"system_id" varchar(100) NOT NULL,
	"title" varchar(255) NOT NULL,
	"content" text NOT NULL,
	"type" varchar(50) NOT NULL,
	"entry_point" boolean DEFAULT false NOT NULL,
	"always_load" boolean DEFAULT false NOT NULL,
	"load_order" integer DEFAULT 0 NOT NULL,
	"dependencies" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"tags" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"version" varchar(50),
	"source_path" varchar(500),
	CONSTRAINT "docs_system_id_unique" UNIQUE("system_id")
);
--> statement-breakpoint
CREATE TABLE "presets" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "presets_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"use_yn" varchar(1) DEFAULT 'Y' NOT NULL,
	"delete_yn" varchar(1) DEFAULT 'N' NOT NULL,
	"create_id" integer,
	"create_date" timestamp with time zone DEFAULT now() NOT NULL,
	"update_id" integer,
	"update_date" timestamp with time zone,
	"delete_id" integer,
	"delete_date" timestamp with time zone,
	"code" varchar(100) NOT NULL,
	"name" varchar(255) NOT NULL,
	"description" text,
	"core_identity" text,
	"recommended_rank" varchar(50),
	"recommended_themes" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"recommended_race_types" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"recommended_class_archetypes" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"recommended_weapons" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"recommended_outfit_style" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"recommended_fx" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"recommended_lighting" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"recommended_backgrounds" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"recommended_mood" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"shape_language" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"rendering_keywords" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"content" text,
	"metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
	CONSTRAINT "presets_code_unique" UNIQUE("code")
);
--> statement-breakpoint
CREATE TABLE "prompts" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "prompts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"use_yn" varchar(1) DEFAULT 'Y' NOT NULL,
	"delete_yn" varchar(1) DEFAULT 'N' NOT NULL,
	"create_id" integer,
	"create_date" timestamp with time zone DEFAULT now() NOT NULL,
	"update_id" integer,
	"update_date" timestamp with time zone,
	"delete_id" integer,
	"delete_date" timestamp with time zone,
	"name" varchar(255) NOT NULL,
	"content" text NOT NULL,
	"tags" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"doc_ids" jsonb DEFAULT '[]'::jsonb NOT NULL
);
--> statement-breakpoint
CREATE TABLE "races" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "races_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"use_yn" varchar(1) DEFAULT 'Y' NOT NULL,
	"delete_yn" varchar(1) DEFAULT 'N' NOT NULL,
	"create_id" integer,
	"create_date" timestamp with time zone DEFAULT now() NOT NULL,
	"update_id" integer,
	"update_date" timestamp with time zone,
	"delete_id" integer,
	"delete_date" timestamp with time zone,
	"code" varchar(100) NOT NULL,
	"name" varchar(255) NOT NULL,
	"description" text,
	"category" varchar(100),
	"anatomy_type" text,
	"body_build" text,
	"surface_traits" text,
	"face_structure" text,
	"silhouette" text,
	"material_traits" text,
	"rendering_keywords" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"content" text,
	"metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
	CONSTRAINT "races_code_unique" UNIQUE("code")
);
--> statement-breakpoint
CREATE TABLE "themes" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "themes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"use_yn" varchar(1) DEFAULT 'Y' NOT NULL,
	"delete_yn" varchar(1) DEFAULT 'N' NOT NULL,
	"create_id" integer,
	"create_date" timestamp with time zone DEFAULT now() NOT NULL,
	"update_id" integer,
	"update_date" timestamp with time zone,
	"delete_id" integer,
	"delete_date" timestamp with time zone,
	"code" varchar(100) NOT NULL,
	"name" varchar(255) NOT NULL,
	"description" text,
	"tier" varchar(100),
	"core_identity" text,
	"primary_colors" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"accent_colors" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"fx_elements" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"lighting_style" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"material_language" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"shape_language" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"atmosphere" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"environmental_influence" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"rendering_keywords" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"content" text,
	"metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
	CONSTRAINT "themes_code_unique" UNIQUE("code")
);
